# Generated by Django 2.0 on 2017-12-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171212_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('angry', models.FloatField()),
                ('fear', models.FloatField()),
                ('happy', models.FloatField()),
                ('sad', models.FloatField()),
                ('surprise', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
    ]
