# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='emotion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.date(2017, 12, 19)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name=b'pub_date',
            field=models.DateTimeField(verbose_name=datetime.date(2017, 12, 19)),
        ),
    ]
